services:
    sonata.admin.manager.propel:
        class: Sonata\PropelAdminBundle\Model\ModelManager

    sonata.admin.builder.propel_form:
        class: Sonata\PropelAdminBundle\Builder\FormContractor
        arguments:
            - '@form.factory'

    sonata.admin.builder.propel_show:
        class: Sonata\PropelAdminBundle\Builder\ShowBuilder

    sonata.admin.builder.propel_list:
        class: Sonata\PropelAdminBundle\Builder\ListBuilder

    sonata.admin.builder.propel_datagrid:
        class: Sonata\PropelAdminBundle\Builder\DatagridBuilder
        arguments:
            - '@form.factory'
