services:
    sonata.admin.propel.filter.type.string:
        class: Sonata\PropelAdminBundle\Filter\StringFilter
        tags:
            - { name: 'sonata.admin.filter.type', alias: 'propel_string' }
            - { name: 'sonata.admin.filter.type', alias: 'propel_varchar' }
            - { name: 'sonata.admin.filter.type', alias: 'propel_longvarchar' }
            - { name: 'sonata.admin.filter.type', alias: 'propel_text' }

    sonata.admin.propel.filter.type.number:
        class: Sonata\PropelAdminBundle\Filter\NumberFilter
        tags:
            - { name: 'sonata.admin.filter.type', alias: 'propel_integer' }
            - { name: 'sonata.admin.filter.type', alias: 'propel_number' }

    sonata.admin.propel.filter.type.model:
        class: Sonata\PropelAdminBundle\Filter\ModelFilter
        tags:
            - { name: 'sonata.admin.filter.type', alias: 'propel_model' }
